module.exports.fakeData = [
    {
        "watching_count": null,
        "olson_path": "America/Los_Angeles",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NV",
        "postal_code": "89104",
        "going_count": null,
        "all_day": "0",
        "latitude": "36.1479690",
        "groups": null,
        "url": "http://lasvegas.eventful.com/events/mj-live-michael-jackson-/E0-001-100488758-4@2017070400?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-100488758-4@2017070400",
        "privacy": "1",
        "city_name": "Las Vegas",
        "link_count": null,
        "longitude": "-115.1553160",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Nevada",
        "start_time": "2017-07-04 00:00:00",
        "tz_id": null,
        "description": " <strong>BestofVegas Special Offer:<br>Save $23 on General Reserved Seating!</strong><br><br><strong>MJ Live: Michael Jackson Tribute Concert</strong><br> Michael Jackson is alive and well as fans can relive his greatest hits and signature dance moves in MJ Live at the Stratosphere. BestofVegas.com can get you great seats to see this wonderful tribute concert. The King of Pop is emulated in every way possible -- his mannerisms, dance moves and the unmistakable voice. Flanked by a bevy of fantastic dancers, MJ Live captures the superstar’s true spirit, showcasing Michael Jackson’s greatest hits like “Billie Jean,” “Beat It,” “Smooth Criminal” and “Thriller.” This is one of the better tribute shows you’ll find in Vegas, so tickets to MJ Live are well worth your time. ",
        "modified": "2017-05-16 14:50:42",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "MJ Live: Michael Jackson Tribute Concert",
        "venue_address": "2000 Las Vegas Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
            "small": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "width": "48",
            "caption": null,
            "medium": {
                "width": "128",
                "url": "http://s4.evcdn.com/images/medium/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "128"
            },
            "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
            "thumb": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/thumb/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "height": "48"
        },

        "created": "2017-02-18 06:28:18",
        "venue_id": "V0-001-000110247-4",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Stratosphere Hotel & Casino",
        "venue_url": "http://lasvegas.eventful.com/venues/stratosphere-hotel-casino-/V0-001-000110247-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
    },
    {
        "watching_count": null,
        "olson_path": "America/Los_Angeles",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NV",
        "postal_code": "89104",
        "going_count": null,
        "all_day": "0",
        "latitude": "36.1479690",
        "groups": null,
        "url": "http://lasvegas.eventful.com/events/mj-live-michael-jackson-/E0-001-100488758-4@2017070400?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-100488758-4@2017070400",
        "privacy": "1",
        "city_name": "Las Vegas",
        "link_count": null,
        "longitude": "-115.1553160",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Nevada",
        "start_time": "2017-07-04 00:00:00",
        "tz_id": null,
        "description": " <strong>BestofVegas Special Offer:<br>Save $23 on General Reserved Seating!</strong><br><br><strong>MJ Live: Michael Jackson Tribute Concert</strong><br> Michael Jackson is alive and well as fans can relive his greatest hits and signature dance moves in MJ Live at the Stratosphere. BestofVegas.com can get you great seats to see this wonderful tribute concert. The King of Pop is emulated in every way possible -- his mannerisms, dance moves and the unmistakable voice. Flanked by a bevy of fantastic dancers, MJ Live captures the superstar’s true spirit, showcasing Michael Jackson’s greatest hits like “Billie Jean,” “Beat It,” “Smooth Criminal” and “Thriller.” This is one of the better tribute shows you’ll find in Vegas, so tickets to MJ Live are well worth your time. ",
        "modified": "2017-05-16 14:50:42",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "MJ Live: Michael Jackson Tribute Concert",
        "venue_address": "2000 Las Vegas Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
            "small": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "width": "48",
            "caption": null,
            "medium": {
                "width": "128",
                "url": "http://s4.evcdn.com/images/medium/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "128"
            },
            "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
            "thumb": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/thumb/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "height": "48"
        },

        "created": "2017-02-18 06:28:18",
        "venue_id": "V0-001-000110247-4",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Stratosphere Hotel & Casino",
        "venue_url": "http://lasvegas.eventful.com/venues/stratosphere-hotel-casino-/V0-001-000110247-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
    },{
        "watching_count": null,
        "olson_path": "America/Los_Angeles",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NV",
        "postal_code": "89104",
        "going_count": null,
        "all_day": "0",
        "latitude": "36.1479690",
        "groups": null,
        "url": "http://lasvegas.eventful.com/events/mj-live-michael-jackson-/E0-001-100488758-4@2017070400?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-100488758-4@2017070400",
        "privacy": "1",
        "city_name": "Las Vegas",
        "link_count": null,
        "longitude": "-115.1553160",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Nevada",
        "start_time": "2017-07-04 00:00:00",
        "tz_id": null,
        "description": " <strong>BestofVegas Special Offer:<br>Save $23 on General Reserved Seating!</strong><br><br><strong>MJ Live: Michael Jackson Tribute Concert</strong><br> Michael Jackson is alive and well as fans can relive his greatest hits and signature dance moves in MJ Live at the Stratosphere. BestofVegas.com can get you great seats to see this wonderful tribute concert. The King of Pop is emulated in every way possible -- his mannerisms, dance moves and the unmistakable voice. Flanked by a bevy of fantastic dancers, MJ Live captures the superstar’s true spirit, showcasing Michael Jackson’s greatest hits like “Billie Jean,” “Beat It,” “Smooth Criminal” and “Thriller.” This is one of the better tribute shows you’ll find in Vegas, so tickets to MJ Live are well worth your time. ",
        "modified": "2017-05-16 14:50:42",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "MJ Live: Michael Jackson Tribute Concert",
        "venue_address": "2000 Las Vegas Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
            "small": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "width": "48",
            "caption": null,
            "medium": {
                "width": "128",
                "url": "http://s4.evcdn.com/images/medium/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "128"
            },
            "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
            "thumb": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/thumb/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "height": "48"
        },

        "created": "2017-02-18 06:28:18",
        "venue_id": "V0-001-000110247-4",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Stratosphere Hotel & Casino",
        "venue_url": "http://lasvegas.eventful.com/venues/stratosphere-hotel-casino-/V0-001-000110247-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
    },{
        "watching_count": null,
        "olson_path": "America/Los_Angeles",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NV",
        "postal_code": "89104",
        "going_count": null,
        "all_day": "0",
        "latitude": "36.1479690",
        "groups": null,
        "url": "http://lasvegas.eventful.com/events/mj-live-michael-jackson-/E0-001-100488758-4@2017070400?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-100488758-4@2017070400",
        "privacy": "1",
        "city_name": "Las Vegas",
        "link_count": null,
        "longitude": "-115.1553160",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Nevada",
        "start_time": "2017-07-04 00:00:00",
        "tz_id": null,
        "description": " <strong>BestofVegas Special Offer:<br>Save $23 on General Reserved Seating!</strong><br><br><strong>MJ Live: Michael Jackson Tribute Concert</strong><br> Michael Jackson is alive and well as fans can relive his greatest hits and signature dance moves in MJ Live at the Stratosphere. BestofVegas.com can get you great seats to see this wonderful tribute concert. The King of Pop is emulated in every way possible -- his mannerisms, dance moves and the unmistakable voice. Flanked by a bevy of fantastic dancers, MJ Live captures the superstar’s true spirit, showcasing Michael Jackson’s greatest hits like “Billie Jean,” “Beat It,” “Smooth Criminal” and “Thriller.” This is one of the better tribute shows you’ll find in Vegas, so tickets to MJ Live are well worth your time. ",
        "modified": "2017-05-16 14:50:42",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "MJ Live: Michael Jackson Tribute Concert",
        "venue_address": "2000 Las Vegas Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
            "small": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "width": "48",
            "caption": null,
            "medium": {
                "width": "128",
                "url": "http://s4.evcdn.com/images/medium/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "128"
            },
            "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
            "thumb": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/thumb/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "height": "48"
        },

        "created": "2017-02-18 06:28:18",
        "venue_id": "V0-001-000110247-4",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Stratosphere Hotel & Casino",
        "venue_url": "http://lasvegas.eventful.com/venues/stratosphere-hotel-casino-/V0-001-000110247-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
    },
    {
        "watching_count": null,
        "olson_path": "America/Los_Angeles",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NV",
        "postal_code": "89104",
        "going_count": null,
        "all_day": "0",
        "latitude": "36.1479690",
        "groups": null,
        "url": "http://lasvegas.eventful.com/events/mj-live-michael-jackson-/E0-001-100488758-4@2017070400?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-100488758-4@2017070400",
        "privacy": "1",
        "city_name": "Las Vegas",
        "link_count": null,
        "longitude": "-115.1553160",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Nevada",
        "start_time": "2017-07-04 00:00:00",
        "tz_id": null,
        "description": " <strong>BestofVegas Special Offer:<br>Save $23 on General Reserved Seating!</strong><br><br><strong>MJ Live: Michael Jackson Tribute Concert</strong><br> Michael Jackson is alive and well as fans can relive his greatest hits and signature dance moves in MJ Live at the Stratosphere. BestofVegas.com can get you great seats to see this wonderful tribute concert. The King of Pop is emulated in every way possible -- his mannerisms, dance moves and the unmistakable voice. Flanked by a bevy of fantastic dancers, MJ Live captures the superstar’s true spirit, showcasing Michael Jackson’s greatest hits like “Billie Jean,” “Beat It,” “Smooth Criminal” and “Thriller.” This is one of the better tribute shows you’ll find in Vegas, so tickets to MJ Live are well worth your time. ",
        "modified": "2017-05-16 14:50:42",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "MJ Live: Michael Jackson Tribute Concert",
        "venue_address": "2000 Las Vegas Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
            "small": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "width": "48",
            "caption": null,
            "medium": {
                "width": "128",
                "url": "http://s4.evcdn.com/images/medium/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "128"
            },
            "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
            "thumb": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/thumb/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "height": "48"
        },

        "created": "2017-02-18 06:28:18",
        "venue_id": "V0-001-000110247-4",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Stratosphere Hotel & Casino",
        "venue_url": "http://lasvegas.eventful.com/venues/stratosphere-hotel-casino-/V0-001-000110247-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
    },
    {
        "watching_count": null,
        "olson_path": "America/Los_Angeles",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NV",
        "postal_code": "89104",
        "going_count": null,
        "all_day": "0",
        "latitude": "36.1479690",
        "groups": null,
        "url": "http://lasvegas.eventful.com/events/mj-live-michael-jackson-/E0-001-100488758-4@2017070400?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-100488758-4@2017070400",
        "privacy": "1",
        "city_name": "Las Vegas",
        "link_count": null,
        "longitude": "-115.1553160",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Nevada",
        "start_time": "2017-07-04 00:00:00",
        "tz_id": null,
        "description": " <strong>BestofVegas Special Offer:<br>Save $23 on General Reserved Seating!</strong><br><br><strong>MJ Live: Michael Jackson Tribute Concert</strong><br> Michael Jackson is alive and well as fans can relive his greatest hits and signature dance moves in MJ Live at the Stratosphere. BestofVegas.com can get you great seats to see this wonderful tribute concert. The King of Pop is emulated in every way possible -- his mannerisms, dance moves and the unmistakable voice. Flanked by a bevy of fantastic dancers, MJ Live captures the superstar’s true spirit, showcasing Michael Jackson’s greatest hits like “Billie Jean,” “Beat It,” “Smooth Criminal” and “Thriller.” This is one of the better tribute shows you’ll find in Vegas, so tickets to MJ Live are well worth your time. ",
        "modified": "2017-05-16 14:50:42",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "MJ Live: Michael Jackson Tribute Concert",
        "venue_address": "2000 Las Vegas Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
            "small": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "width": "48",
            "caption": null,
            "medium": {
                "width": "128",
                "url": "http://s4.evcdn.com/images/medium/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "128"
            },
            "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
            "thumb": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/thumb/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "height": "48"
        },

        "created": "2017-02-18 06:28:18",
        "venue_id": "V0-001-000110247-4",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Stratosphere Hotel & Casino",
        "venue_url": "http://lasvegas.eventful.com/venues/stratosphere-hotel-casino-/V0-001-000110247-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
    },{
        "watching_count": null,
        "olson_path": "America/Los_Angeles",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NV",
        "postal_code": "89104",
        "going_count": null,
        "all_day": "0",
        "latitude": "36.1479690",
        "groups": null,
        "url": "http://lasvegas.eventful.com/events/mj-live-michael-jackson-/E0-001-100488758-4@2017070400?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-100488758-4@2017070400",
        "privacy": "1",
        "city_name": "Las Vegas",
        "link_count": null,
        "longitude": "-115.1553160",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Nevada",
        "start_time": "2017-07-04 00:00:00",
        "tz_id": null,
        "description": " <strong>BestofVegas Special Offer:<br>Save $23 on General Reserved Seating!</strong><br><br><strong>MJ Live: Michael Jackson Tribute Concert</strong><br> Michael Jackson is alive and well as fans can relive his greatest hits and signature dance moves in MJ Live at the Stratosphere. BestofVegas.com can get you great seats to see this wonderful tribute concert. The King of Pop is emulated in every way possible -- his mannerisms, dance moves and the unmistakable voice. Flanked by a bevy of fantastic dancers, MJ Live captures the superstar’s true spirit, showcasing Michael Jackson’s greatest hits like “Billie Jean,” “Beat It,” “Smooth Criminal” and “Thriller.” This is one of the better tribute shows you’ll find in Vegas, so tickets to MJ Live are well worth your time. ",
        "modified": "2017-05-16 14:50:42",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "MJ Live: Michael Jackson Tribute Concert",
        "venue_address": "2000 Las Vegas Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
            "small": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "width": "48",
            "caption": null,
            "medium": {
                "width": "128",
                "url": "http://s4.evcdn.com/images/medium/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "128"
            },
            "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
            "thumb": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/thumb/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "height": "48"
        },

        "created": "2017-02-18 06:28:18",
        "venue_id": "V0-001-000110247-4",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Stratosphere Hotel & Casino",
        "venue_url": "http://lasvegas.eventful.com/venues/stratosphere-hotel-casino-/V0-001-000110247-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
    },{
        "watching_count": null,
        "olson_path": "America/Los_Angeles",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NV",
        "postal_code": "89104",
        "going_count": null,
        "all_day": "0",
        "latitude": "36.1479690",
        "groups": null,
        "url": "http://lasvegas.eventful.com/events/mj-live-michael-jackson-/E0-001-100488758-4@2017070400?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-100488758-4@2017070400",
        "privacy": "1",
        "city_name": "Las Vegas",
        "link_count": null,
        "longitude": "-115.1553160",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Nevada",
        "start_time": "2017-07-04 00:00:00",
        "tz_id": null,
        "description": " <strong>BestofVegas Special Offer:<br>Save $23 on General Reserved Seating!</strong><br><br><strong>MJ Live: Michael Jackson Tribute Concert</strong><br> Michael Jackson is alive and well as fans can relive his greatest hits and signature dance moves in MJ Live at the Stratosphere. BestofVegas.com can get you great seats to see this wonderful tribute concert. The King of Pop is emulated in every way possible -- his mannerisms, dance moves and the unmistakable voice. Flanked by a bevy of fantastic dancers, MJ Live captures the superstar’s true spirit, showcasing Michael Jackson’s greatest hits like “Billie Jean,” “Beat It,” “Smooth Criminal” and “Thriller.” This is one of the better tribute shows you’ll find in Vegas, so tickets to MJ Live are well worth your time. ",
        "modified": "2017-05-16 14:50:42",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "MJ Live: Michael Jackson Tribute Concert",
        "venue_address": "2000 Las Vegas Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
            "small": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "width": "48",
            "caption": null,
            "medium": {
                "width": "128",
                "url": "http://s4.evcdn.com/images/medium/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "128"
            },
            "url": "http://s4.evcdn.com/images/small/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
            "thumb": {
                "width": "48",
                "url": "http://s4.evcdn.com/images/thumb/I0-001/024/825/663-1.jpeg_/mj-live-michael-jackson-tribute-concer-63.jpeg",
                "height": "48"
            },
            "height": "48"
        },

        "created": "2017-02-18 06:28:18",
        "venue_id": "V0-001-000110247-4",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Stratosphere Hotel & Casino",
        "venue_url": "http://lasvegas.eventful.com/venues/stratosphere-hotel-casino-/V0-001-000110247-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
    }
]


